### ISSUE TITLE
Subscribe on specify component - not working

### ISSUE THREAD

**Issue by ngrigoraki** [DivineOmega/cachet.php#37]
$subscriberDetails = ['email' => 'test@test.com', 'verify' => 1 , 'components' => [5,7]];
$subscriber = $cachetInstance->createSubscriber($subscriberDetails);

echo $subscriber->id.' - '.$subscriber->email;

I run this code, but the new Subscriber isn't being subscribed to the supplied component but is Subscribed to all updates.

**Comment by Jord-JD** [comment]
Are you running v0.2?

**Comment by ngrigoraki** [comment]
Hello,

Yes i have downloaded the package from [here](https://packagist.org/packages/divineomega/cachetphp).

composer.json file:
{
    "require": {
        "divineomega/cachetphp": "^0.2.0"
    }
}

**Comment by Jord-JD** [comment]
Hi,

I think the library is working correctly. I've just tested this out using the forms on the official Cachet documentation site, and I'm seeing the same issue. It seems to be ignoring the component ids provided.

You can recreate the issue here:
1. Creating a new subscribe here with one or more component ids: https://docs.cachethq.io/docs/subscribers
2. Reviewing the created subscriber here, subscribed to all component updates: https://docs.cachethq.io/docs/get-subscribers

This might be a bug in Cachet itself. 

@jbrooksuk - If you get a free 10 minutes, would you mind checking if we're doing something wrong here?

**Comment by jbrooksuk** [comment]
@DivineOmega hey! Sorry for the delay, I've been on holiday.

This is fixed in https://github.com/CachetHQ/Cachet/commit/bde0abe

**Comment by Jord-JD** [comment]
@jbrooksuk Thanks for getting back. Hope you had a good holiday. :smile:

**Comment by ngrigoraki** [comment]
Thank you both!
